## code to create lookup mapping package data
## run this script to regenerate data objects: lookup_razao, provincia_map, distrito_map


razao_map <-
  tibble::tribble(
  ~source_file                            , ~descricao                                     , ~provincia              ,
  "CENTRAL EUR.pdf"                       , "Conta 7321000 CUT EUR - MEF"                  , NA                      ,
  "CENTRAL EURO.pdf"                      , "Conta 7321000 CUT EUR - MEF"                  , NA                      ,
  "CENTRAL MT.pdf"                        , "Conta 7321000 CUT MTN - MEF"                  , NA                      ,
  "CENTRAL USD.pdf"                       , "Conta 7321000  CUT USD - MEF"                 , NA                      ,
  "EXTRACTO ABSA BANK MZN.pdf"            , "ABSA BANK MT"                                 , NA                      ,
  "EXTRACTO ABSA BANK MT.pdf"             , "ABSA BANK MT"                                 , NA                      ,
  "EXTRACTO ABSA BANK USD.pdf"            , "ABSA BANK USD"                                , NA                      ,
  "FOREX EUR"                             , "Conta nr.004037601011   EUR  Forex - B.M. "   , NA                      ,
  "FOREX USD"                             , "Conta Especial 004187601014 - USD FOREX B.M." , NA                      ,
  "CABO DELGADO DESCENTRALIZADO.pdf"      , "Cabo Delgado"                                 , "Cabo Delgado"          ,
  "CABO DELGADO.pdf"                      , "Cabo Delgado"                                 , "Cabo Delgado"          ,
  "GAZA DESCENTRALIZADO.pdf"              , "Gaza"                                         , "Gaza"                  ,
  "GAZA.pdf"                              , "Gaza"                                         , "Gaza"                  ,
  "INHAMBANE DESCENTRALIZADO.pdf"         , "Inhambane"                                    , "Inhambane"             ,
  "INHAMBANE.pdf"                         , "Inhambane"                                    , "Inhambane"             ,
  "MANICA DESCENTRALIZADO.pdf"            , "Manica"                                       , "Manica"                ,
  "MANICA.pdf"                            , "Manica"                                       , "Manica"                ,
  "MAPUTO CIDADE.pdf"                     , "Maputo Cidade"                                , "Maputo Cidade"         ,
  "M. PROVINCIA DESCENTRALIZADO.pdf"      , "Maputo Província"                        , "Maputo Província" ,
  "MAPUTO PROVINCIA DESCENTRALIZADO .pdf" , "Maputo Província"                        , "Maputo Província" ,
  "MAPUTO PROVINCIA DESCETRALIZADO.pdf"   , "Maputo Província"                        , "Maputo Província" ,
  "MAPUTO PROVINCIA.pdf"                  , "Maputo Província"                        , "Maputo Província" ,
  "NAMPULA DESCENTRALIZADO.pdf"           , "Nampula"                                      , "Nampula"               ,
  "NAMPULA.pdf"                           , "Nampula"                                      , "Nampula"               ,
  "NIASSA DESCENTRALIZADO.pdf"            , "Niassa"                                       , "Niassa"                ,
  "NIASSA.pdf"                            , "Niassa"                                       , "Niassa"                ,
  "SOFALA DESCENTRALIZADO.pdf"            , "Sofala"                                       , "Sofala"                ,
  "SOFALA.pdf"                            , "Sofala"                                       , "Sofala"                ,
  "TETE DESCENTRALIZADO.pdf"              , "Tete"                                         , "Tete"                  ,
  "TETE.pdf"                              , "Tete"                                         , "Tete"                  ,
  "ZAMBEZIA DESCENTRALIZADO.pdf"          , "Zambézia"                                , "Zambézia"         ,
  "ZAMBEZIA.pdf"                          , "Zambézia"                                , "Zambézia"
)

provincia_map <-
  tibble::tribble(
         ~provincia_fonte, ~provincia_oficial, ~provincia_id,
                 "Niassa",           "Niassa",            1L,
           "Cabo Delgado",     "Cabo Delgado",            2L,
                "Nampula",          "Nampula",            3L,
               "Zambézia",         "Zambézia",            4L,
               "Zambezia",         "Zambézia",            4L,
                   "Tete",             "Tete",            5L,
                 "Manica",           "Manica",            6L,
                 "Sofala",           "Sofala",            7L,
              "Inhambane",        "Inhambane",            8L,
                   "Gaza",             "Gaza",            9L,
            "Maputo Prov", "Maputo Província",           10L,
       "Maputo Província", "Maputo Província",           10L,
       "Maputo Provincia", "Maputo Província",           10L,
                 "Maputo", "Maputo Província",           10L,
          "Maputo Cidade",    "Maputo Cidade",           11L,
       "Cidade de Maputo",    "Maputo Cidade",           11L,
          "Cidade Maputo",    "Maputo Cidade",           11L
       )



distrito_map <-
  tibble::tribble(
                       ~distrito_fonte,                 ~distrito_oficial, ~distrito_id,
                             "Ancuabe",                         "Ancuabe",         101L,
                              "Chiúre",                          "Chiúre",         102L,
                                 "Ibo",                             "Ibo",         103L,
                             "Macomia",                         "Macomia",         104L,
                              "Mecúfi",                          "Mecúfi",         105L,
                              "Meluco",                          "Meluco",         106L,
                   "Mocímboa da Praia",               "Mocímboa da Praia",         107L,
                           "Montepuez",                       "Montepuez",         108L,
                               "Mueda",                           "Mueda",         109L,
                              "Namuno",                          "Namuno",         110L,
                               "Palma",                           "Palma",         111L,
                      "Pemba - Metuge",                  "Pemba - Metuge",         112L,
                           "Quissanga",                       "Quissanga",         113L,
                     "Cidade de Pemba",                 "Cidade de Pemba",         114L,
                     "Cidade De Pemba",                 "Cidade de Pemba",         114L,
                              "Balama",                          "Balama",         115L,
                            "Muidumbe",                        "Muidumbe",         116L,
                             "Nangade",                         "Nangade",         117L,
                             "ChiÃºre",                          "Chiúre",         102L,
                              "Mecufi",                          "Mecúfi",         105L,
                              "Metuge",                  "Pemba - Metuge",         112L,
                  "MocÃ­mboa Da Praia",               "Mocímboa da Praia",         107L,
                   "Mocímboa Da Praia",               "Mocímboa da Praia",         107L,
                              "Cuamba",                          "Cuamba",         201L,
                              "Majune",                          "Majune",         202L,
                            "Mandimba",                        "Mandimba",         203L,
                             "Marrupa",                         "Marrupa",         204L,
                                "Maúa",                            "Maúa",         205L,
                              "Mavago",                          "Mavago",         206L,
                          "Mecanhelas",                      "Mecanhelas",         207L,
                              "Mecula",                          "Mecula",         208L,
                                "Lago",                            "Lago",         209L,
                          "Chimbunila",                      "Chimbunila",         210L,
                            "Lichinga",                        "Lichinga",         211L,
                               "Sanga",                           "Sanga",         212L,
                              "Muembe",                          "Muembe",         213L,
                             "N'Gauma",                         "N'Gauma",         214L,
                              "Ngaúma",                         "N'Gauma",         214L,
                            "Metarica",                        "Metarica",         215L,
                              "Nipepe",                          "Nipepe",         216L,
                          "Chimbonila",                      "Chimbunila",         210L,
                "Distrito De Lichinga",                        "Lichinga",         211L,
                               "MaÃºa",                            "Maúa",         205L,
                             "NgaÃºma",                         "N'Gauma",         214L,
                             "Angoche",                         "Angoche",         301L,
                             "Nacarôa",                         "Nacarôa",         302L,
                  "Ilha de Moçambique",              "Ilha de Moçambique",         303L,
                  "Ilha De Moçambique",              "Ilha de Moçambique",         303L,
                      "Nacala - Porto",                  "Nacala - Porto",         304L,
                              "Malema",                          "Malema",         305L,
                             "Meconta",                         "Meconta",         306L,
                            "Mecubúri",                        "Mecubúri",         307L,
                               "Memba",                           "Memba",         308L,
                           "Mogincual",                       "Mogincual",         309L,
                           "Mogovolas",                       "Mogovolas",         310L,
                                "Moma",                            "Moma",         311L,
                              "Monapo",                          "Monapo",         312L,
                            "Mossuril",                        "Mossuril",         313L,
                             "Muecate",                         "Muecate",         314L,
                           "Murrupula",                       "Murrupula",         315L,
                      "Nacala - Velha",                  "Nacala - Velha",         316L,
                  "Nampula - Distrito",              "Nampula - Distrito",         317L,
                   "Cidade de Nampula",               "Cidade de Nampula",         318L,
                              "Ribaué",                          "Ribaué",         319L,
                              "Lalaua",                          "Lalaua",         320L,
                      "Namapa - Eráti",                  "Namapa - Eráti",         321L,
                               "Larde",                           "Larde",         322L,
                               "Liupo",                           "Liupo",         323L,
                 "Distrito De Nampula",              "Nampula - Distrito",         317L,
                               "Erati",                  "Namapa - Eráti",         321L,
                 "Ilha De MoÃ§ambique",              "Ilha de Moçambique",         303L,
                            "Mecuburi",                        "Mecubúri",         307L,
                      "Nacala-A-Velha",                  "Nacala - Velha",         316L,
                        "Nacala-Porto",                  "Nacala - Porto",         304L,
                             "Nacaroa",                         "Nacarôa",         302L,
                              "Rapale",               "Cidade de Nampula",         318L,
                              "Ribaue",                          "Ribaué",         319L,
                        "Alto Molócué",                    "Alto Molócué",         401L,
                        "Alto Molócuè",                    "Alto Molócué",         401L,
                              "Chinde",                          "Chinde",         402L,
                                "Gilé",                            "Gilé",         403L,
                               "Gurué",                           "Gurué",         404L,
                                 "Ile",                             "Ile",         405L,
                              "Lugela",                          "Lugela",         406L,
                    "Maganja da Costa",                "Maganja da Costa",         407L,
                    "Maganja Da Costa",                "Maganja da Costa",         407L,
                             "Milange",                         "Milange",         408L,
                              "Mocuba",                          "Mocuba",         409L,
                              "Mopeia",                          "Mopeia",         410L,
                          "Morrumbala",                      "Morrumbala",         411L,
                           "Namacurra",                       "Namacurra",         412L,
                            "Namarroi",                        "Namarroi",         413L,
                              "Pebane",                          "Pebane",         414L,
                 "Cidade de Quelimane",             "Cidade de Quelimane",         415L,
                 "Cidade De Quelimane",             "Cidade de Quelimane",         415L,
                           "Nicoadala",                       "Nicoadala",         416L,
                         "Inhassungue",                     "Inhassungue",         417L,
                               "Luabo",                           "Luabo",         418L,
                            "Mocubela",                        "Mocubela",         419L,
                            "Mulevala",                        "Mulevala",         420L,
                             "Molumbo",                         "Molumbo",         421L,
                               "Derre",                           "Derre",         422L,
                           "Quelimane",             "Cidade de Quelimane",         415L,
                      "Alto MolÃ³cuÃ¨",                    "Alto Molócué",         401L,
                               "GilÃ©",                            "Gilé",         403L,
                              "GuruÃ©",                           "Gurué",         404L,
                          "Inhassunge",                     "Inhassungue",         417L,
                             "Angónia",                         "Angónia",         501L,
                        "Cahora Bassa",                    "Cahora Bassa",         502L,
                              "Chiúta",                          "Chiúta",         503L,
                             "Macanga",                         "Macanga",         504L,
                             "Marávia",                         "Marávia",         505L,
                             "Moatize",                         "Moatize",         506L,
                               "Mágoé",                           "Mágoé",         507L,
                               "Mágoè",                           "Mágoé",         507L,
                            "Mutarara",                        "Mutarara",         508L,
                      "Cidade de Tete",                  "Cidade de Tete",         509L,
                      "Cidade De Tete",                  "Cidade de Tete",         509L,
                               "Zumbo",                           "Zumbo",         510L,
                            "Changara",                        "Changara",         511L,
                            "Tsangano",                        "Tsangano",         512L,
                            "Chifunde",                        "Chifunde",         513L,
                                 "Dôa",                             "Dôa",         514L,
                              "Marara",                          "Marara",         515L,
                            "AngÃ³nia",                         "Angónia",         501L,
                              "Chiuta",                          "Chiúta",         503L,
                                 "Doa",                             "Dôa",         514L,
                            "MarÃ¡via",                         "Marávia",         505L,
                             "MÃ¡goÃ¨",                           "Mágoé",         507L,
                               "Bárué",                           "Bárué",         601L,
                               "Bárue",                           "Bárué",         601L,
                             "Gondola",                         "Gondola",         602L,
                   "Cidade de Chimoio",               "Cidade de Chimoio",         603L,
                   "Cidade De Chimoio",               "Cidade de Chimoio",         603L,
                                "Guro",                            "Guro",         604L,
                              "Manica",                          "Manica",         605L,
                           "Mossurize",                       "Mossurize",         606L,
                         "Sussundenga",                     "Sussundenga",         607L,
                             "Tambara",                         "Tambara",         608L,
                             "Machaze",                         "Machaze",         609L,
                             "Macossa",                         "Macossa",         610L,
                              "Macate",                          "Macate",         611L,
                             "Vanduzi",                         "Vanduzi",         612L,
                              "BÃ¡rue",                           "Bárué",         601L,
                     "Cidade da Beira",                 "Cidade da Beira",         701L,
                     "Cidade Da Beira",                 "Cidade da Beira",         701L,
                                "Búzi",                            "Búzi",         702L,
                                "Caia",                            "Caia",         703L,
                              "Chemba",                          "Chemba",         704L,
                          "Cheringoma",                      "Cheringoma",         705L,
                              "Muanza",                          "Muanza",         706L,
                           "Chibabava",                       "Chibabava",         707L,
                            "Machanga",                        "Machanga",         708L,
                               "Dondo",                           "Dondo",         709L,
                          "Nhamatanda",                      "Nhamatanda",         710L,
                           "Gorongosa",                       "Gorongosa",         711L,
                            "Maríngue",                        "Maríngue",         712L,
                            "Marromeu",                        "Marromeu",         713L,
                               "BÃºzi",                            "Búzi",         702L,
                           "MarÃ­ngue",                        "Maríngue",         712L,
                              "Govuro",                          "Govuro",         801L,
                              "Mabote",                          "Mabote",         802L,
                             "Homoíne",                         "Homoíne",         803L,
                 "Cidade de Inhambane",             "Cidade de Inhambane",         804L,
                 "Cidade De Inhambane",             "Cidade de Inhambane",         804L,
                             "Jangamo",                         "Jangamo",         805L,
                           "Inharrime",                       "Inharrime",         806L,
                            "Massinga",                        "Massinga",         807L,
                          "Funhalouro",                      "Funhalouro",         808L,
                          "Morrumbene",                      "Morrumbene",         809L,
                               "Panda",                           "Panda",         810L,
                           "Vilankulo",                       "Vilankulo",         811L,
                              "Zavala",                          "Zavala",         812L,
                    "Cidade da Maxixe",                "Cidade da Maxixe",         813L,
                           "Inhassoro",                       "Inhassoro",         814L,
                             "Homoine",                         "Homoíne",         803L,
                              "Maxixe",                "Cidade da Maxixe",         813L,
                          "Vilankulos",                       "Vilankulo",         811L,
                      "Bilene - Macia",                  "Bilene - Macia",         901L,
                               "Guijá",                           "Guijá",         902L,
                             "Chibuto",                         "Chibuto",         903L,
                       "Chicualacuala",                   "Chicualacuala",         904L,
                           "Chongoene",                       "Chongoene",         905L,
                              "Chokwe",                          "Chokwe",         906L,
                 "Manjacaze - Dingane",             "Manjacaze - Dingane",         907L,
                           "Massingir",                       "Massingir",         908L,
                   "Cidade de Xai-Xai",               "Cidade de Xai-Xai",         909L,
                   "Cidade De Xai-Xai",               "Cidade de Xai-Xai",         909L,
                             "Chigubo",                         "Chigubo",         910L,
                            "Mabalane",                        "Mabalane",         911L,
                          "Massangena",                      "Massangena",         912L,
                               "Mapai",                           "Mapai",         913L,
                             "Limpopo",                         "Limpopo",         914L,
                              "Bilene",                  "Bilene - Macia",         901L,
                             "ChokwÃ©",                          "Chokwe",         906L,
                              "Chokwé",                          "Chokwe",         906L,
                              "GuijÃ¡",                           "Guijá",         902L,
                          "Mandlakazi",             "Manjacaze - Dingane",         907L,
                               "Boane",                           "Boane",        1001L,
                              "Magude",                          "Magude",        1002L,
                             "Manhiça",                         "Manhiça",        1003L,
                          "Marracuene",                      "Marracuene",        1004L,
                           "Matutuíne",                       "Matutuíne",        1005L,
                           "Matutuìne",                       "Matutuíne",        1005L,
                              "Moamba",                          "Moamba",        1006L,
                            "Namaacha",                        "Namaacha",        1007L,
                    "Cidade da Matola",                "Cidade da Matola",        1008L,
                            "ManhiÃ§a",                         "Manhiça",        1003L,
                              "Matola",                "Cidade da Matola",        1008L,
                          "MatutuÃ¬ne",                       "Matutuíne",        1005L,
            "Municipal KaMfumo (DU 1)",        "Municipal KaMfumo (DU 1)",        1101L,
     "Municipal de Nhlamankulo (DU 2)", "Municipal de Nhlamankulo (DU 2)",        1102L,
         "Municipal KaMaxakeni (DU 3)",     "Municipal KaMaxakeni (DU 3)",        1103L,
          "Municipal Ka Mavota (DU 4)",      "Municipal Ka Mavota (DU 4)",        1104L,
        "Municipal KaMubukwana (DU 5)",    "Municipal KaMubukwana (DU 5)",        1105L,
                   "Municipal KaTembe",               "Municipal KaTembe",        1106L,
                 "Municipal de Inhaca",             "Municipal de Inhaca",        1107L,
                            "Kamavota",      "Municipal Ka Mavota (DU 4)",        1104L,
                          "Kamaxakene",     "Municipal KaMaxakeni (DU 3)",        1103L,
                            "Kampfumo",        "Municipal KaMfumo (DU 1)",        1101L,
                         "Kamubukwana",    "Municipal KaMubukwana (DU 5)",        1105L,
                             "Kanyaka",             "Municipal de Inhaca",        1107L,
                             "Katembe",               "Municipal KaTembe",        1106L,
                         "Nlhamankulu", "Municipal de Nhlamankulo (DU 2)",        1102L
     )



usethis::use_data(razao_map, distrito_map, provincia_map, overwrite = TRUE)
